import { useRef } from 'react';

export default function HealsThePlanet() {
    const steps = [
        {
            id: 'intro',
            heading: "How AI Actively Heals the Planet",
            sub: "Beyond efficiency, AI is driving revolutionary solutions for a sustainable future.",
            isIntro: true
        },
        {
            id: 'step1',
            heading: "AI’s contribution to a more sustainable power grid.",
            content: [
                "Predicting wind energy output: Google Deepmind have shown that Deepmind(Google's AI Research Team) can predict how much energy will be generated by wind 36 hours beforehand making the value of the energy go up by 20% as it can be more effectively distributed.",
                "Energy Distribution: Ai is what controls the energy in the national grid and can move energy around the country instantly which means there is no wasted or surplus energy."
            ]
        },
        {
            id: 'step2',
            heading: "Assistance in researching materials",
            intro: "When humans are researching more efficient batteries and solar cells it takes humans tens of years of trial and error.",
            content: [
                "The discovery engine: AI can simulate chemical combinations way quicker than in real life taking only days for ai to complete this is helping to make current batteries more efficient with the BBC saying “the material could potentially reduce lithium use by up to 70%” and it could even find alternatives altogether meaning a stop in mining rare metals which are destructive to the environment to mine."
            ]
        },
        {
            id: 'step3',
            heading: "Saving Water at Scale",
            intro: "As stated earlier a hamburger uses 660 gallons of water to be made and Artificial Intelligence is significantly reducing that:",
            content: [
                "Smart Irrigation: AI uses satellite imagery and soil sensors so that it can water the plants that need water this helps as instead of having sprinklers which water all the plants including ones that don't need water instead the AI only waters the plants that need water saving around 30%-50% in agricultural water waste.",
                "Pesticide Reduction: AI Guided robots can find and kill individual weeds which mean harmful chemical sprays can be used 90% less."
            ]
        }
    ];

    return (
        <div className="bg-black text-white">
            {steps.map((step, index) => (
                <section
                    key={step.id}
                    className="min-h-screen flex flex-col items-center justify-center p-4 md:p-12 bg-black border-b border-white/10"
                >
                    <div
                        className="max-w-7xl mx-auto text-center flex flex-col items-center gap-12"
                    >
                        {step.isIntro ? (
                            <>
                                <h2 className="text-5xl md:text-9xl font-bold mb-6 bg-gradient-to-b from-green-400 to-emerald-600 bg-clip-text text-transparent leading-tight">
                                    {step.heading}
                                </h2>
                                <p className="text-2xl md:text-4xl text-gray-400 max-w-4xl mx-auto leading-normal">
                                    {step.sub}
                                </p>
                                <div className="mt-20 animate-bounce">
                                    <div className="w-8 h-12 border-2 border-white/20 rounded-full flex justify-center mx-auto">
                                        <div className="w-1 h-3 bg-white rounded-full mt-2" />
                                    </div>
                                </div>
                            </>
                        ) : (
                            <>
                                <h3 className="text-4xl md:text-6xl font-bold mb-10 text-emerald-400 select-none">
                                    {step.heading}
                                </h3>

                                {step.intro && (
                                    <p className="text-2xl md:text-3xl text-gray-300 mb-12 font-light italic max-w-5xl leading-relaxed">
                                        {step.intro}
                                    </p>
                                )}

                                <ul className="flex flex-col gap-12 text-left w-full max-w-6xl px-4 md:px-0">
                                    {step.content.map((point, i) => (
                                        <li key={i} className="flex gap-8 items-start">
                                            {/* Custom HUGE Bullet Point */}
                                            <span className="shrink-0 w-6 h-6 mt-3 rounded-full bg-emerald-400 shadow-[0_0_20px_rgba(52,211,153,0.8)]" />

                                            <p className="text-2xl md:text-4xl text-gray-100 leading-relaxed font-light">
                                                {point}
                                            </p>
                                        </li>
                                    ))}
                                </ul>
                            </>
                        )}
                    </div>
                </section>
            ))}
        </div>
    );
}
