import Hero from './components/Hero';
import Evidence from './components/Evidence';
import Footer from './components/Footer';

// Define HealsThePlanet LOCALLY to ensure no import caching issues
function HealsThePlanetLocal() {
  const steps = [
    {
      id: 'intro',
      heading: "How AI Actively Heals the Planet",
      sub: "Beyond efficiency, AI is driving revolutionary solutions for a sustainable future.",
      isIntro: true
    },
    {
      id: 'step1',
      heading: "AI’s contribution to a more sustainable power grid.",
      content: [
        "Predicting wind energy output: Google Deepmind have shown that Deepmind(Google's AI Research Team) can predict how much energy will be generated by wind 36 hours beforehand making the value of the energy go up by 20% as it can be more effectively distributed.",
        "Energy Distribution: Ai is what controls the energy in the national grid and can move energy around the country instantly which means there is no wasted or surplus energy."
      ]
    },
    {
      id: 'step2',
      heading: "Assistance in researching materials",
      intro: "When humans are researching more efficient batteries and solar cells it takes humans tens of years of trial and error.",
      content: [
        "The discovery engine: AI can simulate chemical combinations way quicker than in real life taking only days for ai to complete this is helping to make current batteries more efficient with the BBC saying “the material could potentially reduce lithium use by up to 70%” and it could even find alternatives altogether meaning a stop in mining rare metals which are destructive to the environment to mine."
      ]
    },
    {
      id: 'step3',
      heading: "Saving Water at Scale",
      intro: "As stated earlier a hamburger uses 660 gallons of water to be made and Artificial Intelligence is significantly reducing that:",
      content: [
        "Smart Irrigation: AI uses satellite imagery and soil sensors so that it can water the plants that need water this helps as instead of having sprinklers which water all the plants including ones that don't need water instead the AI only waters the plants that need water saving around 30%-50% in agricultural water waste.",
        "Pesticide Reduction: AI Guided robots can find and kill individual weeds which mean harmful chemical sprays can be used 90% less."
      ]
    }
  ];

  return (
    <div style={{ backgroundColor: 'black', color: 'white' }}>
      {steps.map((step) => (
        <section
          key={step.id}
          style={{
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '3rem',
            backgroundColor: 'black',
            borderBottom: '1px solid rgba(255,255,255,0.1)',
            position: 'relative'
          }}
        >
          <div style={{
            maxWidth: '1100px',
            margin: '0 auto',
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '2.5rem'
          }}>
            {step.isIntro ? (
              <>
                <h2 style={{
                  fontSize: 'clamp(3rem, 6vw, 6rem)',
                  fontWeight: 'bold',
                  backgroundImage: 'linear-gradient(to bottom, #16a34a, #14532d)', // Forest Gradient
                  WebkitBackgroundClip: 'text',
                  backgroundClip: 'text',
                  color: 'transparent',
                  WebkitTextFillColor: 'transparent',
                  lineHeight: '1.1',
                  display: 'inline-block' // Ensures clip works on block
                }}>
                  {step.heading}
                </h2>
                <p style={{
                  fontSize: 'clamp(1.35rem, 2.5vw, 2rem)',
                  color: '#9ca3af',
                  maxWidth: '800px',
                  margin: '0 auto',
                  lineHeight: '1.5'
                }}>
                  {step.sub}
                </p>
              </>
            ) : (
              <>
                <h3 style={{
                  fontSize: 'clamp(2.25rem, 4.5vw, 3.5rem)',
                  fontWeight: 'bold',
                  color: '#15803d', // Green-700 (Forest Green)
                  lineHeight: '1.15',
                  maxWidth: '900px'
                }}>
                  {step.heading}
                </h3>

                {step.intro && (
                  <p style={{
                    fontSize: 'clamp(1.25rem, 2vw, 1.6rem)',
                    color: 'rgba(255,255,255,0.9)',
                    fontStyle: 'italic',
                    maxWidth: '860px',
                    lineHeight: '1.6'
                  }}>
                    {step.intro}
                  </p>
                )}

                <ul style={{
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '1.5rem',
                  textAlign: 'left',
                  width: '100%',
                  maxWidth: '960px',
                  listStyle: 'none',
                  marginTop: '0.5rem'
                }}>
                  {step.content.map((point, i) => (
                    <li key={i} style={{
                      display: 'flex',
                      gap: '1.5rem',
                      alignItems: 'flex-start',
                      padding: '1.75rem 2rem',
                      borderRadius: '16px',
                      backgroundColor: 'rgba(22,163,74,0.06)',
                      border: '1px solid rgba(22,163,74,0.2)'
                    }}>
                      {/* Custom bullet point via inline styles */}
                      <span style={{
                        flexShrink: 0,
                        width: '1rem',
                        height: '1rem',
                        marginTop: '0.5rem',
                        borderRadius: '50%',
                        backgroundColor: '#16a34a', // Green-600 (Forest Green)
                        boxShadow: '0 0 16px rgba(22,163,74,0.5)' // Green glow
                      }} />

                      <p style={{
                        fontSize: 'clamp(1.1rem, 1.6vw, 1.4rem)',
                        color: '#ffffff', // pure white
                        lineHeight: '1.65',
                        fontWeight: '300'
                      }}>
                        {point}
                      </p>
                    </li>
                  ))}
                </ul>
              </>
            )}
          </div>
        </section>
      ))}
    </div>
  );
}

function App() {
  return (
    <main style={{ backgroundColor: '#000', minHeight: '100vh', color: '#fff' }}>
      <Hero />

      <Evidence />
      {/* Use the local version to force update */}
      <HealsThePlanetLocal />
      <Footer />
    </main>
  );
}

export default App;
